coverage:
    status:
        project:
            default:
                target: 80%
                threshold: 1%
ignore:
    - "src/token/TokenNftsUpdateTransaction.js"
    - "src/account/AccountAllowanceAdjustTransaction.js"
    - "src/account/LiveHashAddTransaction.js"
    - "src/account/LiveHashDeleteTransaction.js"
    - "src/account/LiveHashQuery.js"
    - "src/system/SystemUndeleteTransaction.js"
    - "src/system/SystemDeleteTransaction.js"
