name: Build & Test
on:
    push:
        branches:
            - main
            - develop
            - release/*
            - integration-test-workflow
    pull_request:
        branches:
            - main
            - develop
            - release/*

defaults:
    run:
        shell: bash

permissions:
    contents: read
    pull-requests: write

env:
    CG_EXEC: ionice -c 2 -n 2 nice -n 19

jobs:
    build:
        name: Build using Node ${{ matrix.node }}
        runs-on: hiero-client-sdk-linux-medium
        strategy:
            matrix:
                node: ["20", "22"]

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                  egress-policy: audit

            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  submodules: true

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
              with:
                  version: 3.35.1

            # Note: After Step-Security is enabled return to step-security/action-setup version
            - name: Install PNPM
              uses: step-security/action-setup@1beb3ebc4de86b0e37560725eeef1b11332702a3 # v4.0.1
              with:
                  version: 9.15.5

            - name: Setup Node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ matrix.node }}
                  cache: pnpm

            - name: Build @hashgraph/sdk
              run: task -v build

    test-integration:
        name: Run Integration Tests
        runs-on: hiero-client-sdk-linux-large
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/sdk
              id: build-sdk
              run: task build

            - name: Start the local node
              id: start-local-node
              run: |
                  ${{ env.CG_EXEC }} npx @hashgraph/hedera-local start -d -—network local --balance=100000 --network-tag=0.61.4
                  sleep 30

            - name: Run Hedera SDK Integration Tests
              run: ${{ env.CG_EXEC }} task test:integration:codecov

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage/lcov.info
                  fail_ci_if_error: false

    test-unit-sdk:
        name: Run SDK Unit Tests
        runs-on: hiero-client-sdk-linux-medium
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/sdk
              run: task build

            - name: Codecov @hashgraph/sdk
              run: ${{ env.CG_EXEC }} task test:unit:codecov

            - name: Upload @hashgraph/sdk coverage
              uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true

    test-browser:
        name: Run Browser Tests
        runs-on: hiero-client-sdk-linux-medium
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/sdk
              run: task build

            - name: Install Playwright Dependencies
              run: |
                  sudo npx playwright install-deps
                  npx playwright install

            - name: Browser Unit Test @hashgraph/sdk
              run: ${{ env.CG_EXEC }} task test:unit:browser

    test-cryptography:
        name: Run Cryptography Tests
        runs-on: hiero-client-sdk-linux-medium
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/cryptography
              working-directory: packages/cryptography
              run: ${{ env.CG_EXEC }} task build

            - name: Browser Unit Test @hashgraph/cryptography
              working-directory: packages/cryptography
              run: ${{ env.CG_EXEC }} task test:unit:browser

            - name: Codecov @hashgraph/cryptography
              working-directory: packages/cryptography
              run: ${{ env.CG_EXEC }} task test:unit:codecov

            - name: Upload @hashgraph/cryptography coverage
              uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./packages/cryptography/coverage/lcov.info
                  fail_ci_if_error: false

    examples:
        name: Run examples using Node ${{ matrix.node }}
        runs-on: hiero-client-sdk-linux-medium
        strategy:
            matrix:
                node: ["20"]
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                  egress-policy: audit

            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
              with:
                  version: 3.35.1

            - name: Install PNPM
              uses: step-security/action-setup@1beb3ebc4de86b0e37560725eeef1b11332702a3 # v4.0.1
              with:
                  version: 9.15.5

            - name: Setup Node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ matrix.node }}
                  cache: pnpm

            - name: Build @hashgraph/sdk
              id: build-sdk
              run: task build

            - name: Start the local node
              id: start-local-node
              if: ${{ !cancelled() && always() }}
              run: |
                  ${{ env.CG_EXEC }} npx @hashgraph/hedera-local start -d -—network local --balance=100000 --network-tag=0.61.4
                  sleep 30

            - name: Install dependencies
              run: |
                  cd examples
                  pnpm i

            - name: Run all еxamples
              run: task run:examples
            - name: Stop the local node
              id: stop-local-node
              if: ${{ steps.start-local-node.conclusion == 'success' && !cancelled() && always() }}
              run: ${{ env.CG_EXEC }} npx @hashgraph/hedera-local stop

    test-integration:
        needs: [build]
        name: Run Integration Tests
        runs-on: hiero-client-sdk-linux-large
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/sdk
              id: build-sdk
              run: task build

            - name: Start the local node
              id: start-local-node
              run: |
                  ${{ env.CG_EXEC }} npx @hashgraph/hedera-local start -d -—network local --balance=100000 --network-tag=0.61.4
                  sleep 30

            - name: Run Hedera SDK Integration Tests
              run: ${{ env.CG_EXEC }} task test:integration:codecov

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage/lcov.info
                  fail_ci_if_error: false

    test-unit-sdk:
        needs: [build]
        name: Run SDK Unit Tests
        runs-on: hiero-client-sdk-linux-medium
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/sdk
              run: task build

            - name: Codecov @hashgraph/sdk
              run: ${{ env.CG_EXEC }} task test:unit:codecov

            - name: Upload @hashgraph/sdk coverage
              uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true

    test-browser:
        needs: [build]
        name: Run Browser Tests
        runs-on: hiero-client-sdk-linux-medium
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/sdk
              run: task build

            - name: Install Playwright Dependencies
              run: |
                  sudo npx playwright install-deps
                  npx playwright install

            - name: Browser Unit Test @hashgraph/sdk
              run: ${{ env.CG_EXEC }} task test:unit:browser

    test-cryptography:
        needs: [build]
        name: Run Cryptography Tests
        runs-on: hiero-client-sdk-linux-medium
        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
              with:
                  version: 3.35.1

            - name: Build @hashgraph/cryptography
              working-directory: packages/cryptography
              run: ${{ env.CG_EXEC }} task build

            - name: Browser Unit Test @hashgraph/cryptography
              working-directory: packages/cryptography
              run: ${{ env.CG_EXEC }} task test:unit:browser

            - name: Codecov @hashgraph/cryptography
              working-directory: packages/cryptography
              run: ${{ env.CG_EXEC }} task test:unit:codecov

            - name: Upload @hashgraph/cryptography coverage
              uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./packages/cryptography/coverage/lcov.info
                  fail_ci_if_error: false

    examples:
        name: Run examples using Node ${{ matrix.node }}
        runs-on: hiero-client-sdk-linux-medium
        strategy:
            matrix:
                node: ["20"]
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                  egress-policy: audit

            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  submodules: recursive

            - name: Install Task
              uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
              with:
                  version: 3.35.1

            - name: Install PNPM
              uses: step-security/action-setup@1beb3ebc4de86b0e37560725eeef1b11332702a3 # v4.0.1
              with:
                  version: 9.15.5

            - name: Setup Node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: ${{ matrix.node }}
                  cache: pnpm

            - name: Build @hashgraph/sdk
              id: build-sdk
              run: task build

            - name: Start the local node
              id: start-local-node
              if: ${{ !cancelled() && always() }}
              run: |
                  ${{ env.CG_EXEC }} npx @hashgraph/hedera-local start -d -—network local --balance=100000 --network-tag=0.61.4
                  sleep 30

            - name: Install dependencies
              run: |
                  cd examples
                  pnpm i

            - name: Run all еxamples
              run: task run:examples
            - name: Stop the local node
              id: stop-local-node
              if: ${{ steps.start-local-node.conclusion == 'success' && !cancelled() && always() }}
              run: ${{ env.CG_EXEC }} npx @hashgraph/hedera-local stop
